FROM node:13
WORKDIR /usr/app
ADD .eslintignore /usr/app/.eslintignore
ADD .eslintrc.json /usr/app/.eslintrc.json
ADD package.json /usr/app/package.json
ADD package-lock.json /usr/app/package-lock.json
RUN npm i
ADD public /usr/app/public
ADD src /usr/app/src
CMD npm start
