FROM node:13
WORKDIR /usr/app
ADD .eslintignore /usr/app/.eslintignore
ADD .eslintrc.json /usr/app/.eslintrc.json
ADD package.json /usr/app/package.json
ADD package-lock.json /usr/app/package-lock.json
RUN npm i
ADD index.js /usr/app/index.js
ADD routes /usr/app/routes
ADD services /usr/app/services
ADD middleware /usr/app/middleware
CMD npm start
